name: easy_converter
description: Application for easy currency conversion.


publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  flutter_slidable: ^1.2.1
  cupertino_icons: ^1.0.2
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  build_runner: ^2.1.10
  flutter_launcher_icons: "^0.9.2"


flutter_icons:
  image_path_ios: 'assets/images/ios_icon/iTunesArtwork@3x.png'
  image_path_android: 'assets/images/android_icon/ic_launcher.png'
  adaptive_icon_foreground: 'assets/images/android_icon/ic_launcher_foreground.png'
  adaptive_icon_background: "#ffffff"
  android: true
  ios: true


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/flags/
    - assets/vectors/icons/


  fonts:
    - family: Roboto-Bold
      fonts:
        - asset: font/Roboto-Bold.ttf
    - family: Roboto-Light
      fonts:
        - asset: font/Roboto-Light.ttf

