// назначение папки domain немного сложно понять.
// тут лежат 2 источника данных all_currencies_list и selected_currencies (что-то типа in-memory cache)
// моделька - currency
// и rate_currencies, который делает часть функций репозитория.
//
// я бы разделил первые два в отдельные папки, а код из третьего бы отправил в CurrenciesRepository вместе с кодом из updateRateCurrencies и других подобных методов.

import 'package:easy_converter/resources/resources.dart';

import 'currency.dart';

class AllCurrenciesList {
  static final allCurrenciesList = <String, Currency>{
    "AED": Currency(code: "AED", flag: SvgsFlags.unitedArabEmirates, symbol: 'Dh', title: 'Дирхам ОАЭ', country: 'ОАЭ'),
    "AFN": Currency(code: "AFN", flag: SvgsFlags.afghanistan, symbol: '؋',title: 'Афгани', country: 'Афганистан'),
    "ALL": Currency(code: "ALL", flag: SvgsFlags.albania, symbol: 'L', title: 'Лек', country: 'Албания'),
    "AMD": Currency(code: "AMD", flag: SvgsFlags.armenia, symbol: '֏', title: 'Армянский драм', country: 'Армения'),
    "ANG": Currency(code: "ANG", flag: SvgsFlags.sintMaarten, symbol: 'ƒ', title: 'Нидерландский антильский гульден', country: 'Синт-Мартен'),
    "AOA": Currency(code: "AOA", flag: SvgsFlags.angola, symbol: 'Kz', title: 'Кванза', country: 'Ангола'),
    "ARS": Currency(code: "ARS", flag: SvgsFlags.argentina, symbol: '\$', title: 'Аргентинское песо', country: 'Аргентина'),
    "AUD": Currency(code: "AUD", flag: SvgsFlags.australia, symbol: '\$', title: 'Австралийский доллар', country: 'Австралия'),
    "AWG": Currency(code: "AWG", flag: SvgsFlags.aruba, symbol: 'ƒ', title: 'Арубанский флорин', country: 'Аруба'),
    "AZN": Currency(code: "AZN", flag: SvgsFlags.azerbaijan, symbol: '₼', title: 'Азербайджанский манат', country: 'Азербайджан'),
    "BAM": Currency(code: "BAM", flag: SvgsFlags.bosniaAndHerzegovina, symbol: 'Km', title: 'Конвертируемая марка', country: 'Босния и Герцеговина'),
    "BBD": Currency(code: "BBD", flag: SvgsFlags.barbados, symbol: '\$', title: 'Барбадосский доллар', country: 'Барбадос'),
    "BDT": Currency(code: "BDT", flag: SvgsFlags.bangladesh, symbol: '৳', title: 'Така', country: 'Бангладеш'),
    "BGN": Currency(code: "BGN", flag: SvgsFlags.bulgaria, symbol: 'Лв', title: 'Болгарский лев', country: 'Болгария'),
    "BHD": Currency(code: "BHD", flag: SvgsFlags.bahrain, symbol: 'Bd', title: 'Бахрейнский динар', country: 'Бахрейн'),
    "BIF": Currency(code: "BIF", flag: SvgsFlags.burundi, symbol: '₣', title: 'Бурундийский франк', country: 'Бурунди'),
    "BMD": Currency(code: "BMD", flag: SvgsFlags.bermuda, symbol: '\$', title: 'Бермудский доллар', country: 'Бермуды'),
    "BND": Currency(code: "BND",flag: SvgsFlags.brunei, symbol: '\$', title: 'Брунейский доллар', country: 'Бруней'),
    "BOB": Currency(code: "BOB",flag: SvgsFlags.bolivia, symbol: 'Bs', title: 'Боливиано', country: 'Боливия'),
    "BRL": Currency(code: "BRL",flag: SvgsFlags.brazil, symbol: 'R\$', title: 'Бразильский реал', country: 'Бразилия'),
    "BSD": Currency(code: "BSD",flag: SvgsFlags.bahamas, symbol: '\$', title: 'Багамский доллар', country: 'Багамские Острова'),
    "BTC": Currency(code: "BTC", flag: SvgsFlags.bitcoin, symbol: '₿', title: 'Биткойн', country: 'Bitcion'),
    "BTN": Currency(code: "BTN",flag: SvgsFlags.bhutan, symbol: 'Nu', title: 'Нгултрум', country: 'Бутан'),
    "BTS": Currency(code: "BTS",flag: SvgsFlags.bitshares, symbol: 'BS', title: 'BitShares', country: 'BitShares'),
    "BWP": Currency(code: "BWP",flag: SvgsFlags.botswana, symbol: 'P', title: 'Пула', country: 'Ботсвана'),
    "BYN": Currency(code: "BYN",flag: SvgsFlags.belarus, symbol: 'Br', title: 'Белорусский рубль', country: 'Белоруссия'),
    "BZD": Currency(code: "BZD",flag: SvgsFlags.belize, symbol: 'Bz', title: 'Белизский доллар', country: 'Белиз'),
    "CAD": Currency(code: "CAD",flag: SvgsFlags.canada, symbol: 'C\$', title: 'Канадский доллар', country: 'Канада'),
    "CDF": Currency(code: "CDF",flag: SvgsFlags.democraticRepublicOfCongo , symbol: '₣', title: 'Конголезский франк', country: 'ДР Конго'),
    "CHF": Currency(code: "CHF",flag: SvgsFlags.switzerland , symbol: '₣', title: 'Швейцарский франк', country: 'Швейцария'),
    "CLP": Currency(code: "CLP",flag: SvgsFlags.chile , symbol: '\$', title: 'Чилийское песо', country: 'Чили'),
    "CNY": Currency(code: "CNY",flag: SvgsFlags.china , symbol: '¥', title: 'Юань', country: 'Китай'),
    "COP": Currency(code: "COP",flag: SvgsFlags.colombia , symbol: '\$', title: 'Колумбийское песо', country: 'Колумбия'),
    "CRC": Currency(code: "CRC",flag: SvgsFlags.costaRica , symbol: '₡', title: 'Коста-риканский колон', country: 'Коста-Рика'),
    "CUP": Currency(code: "CUP",flag: SvgsFlags.cuba , symbol: 'Mn', title: 'Кубинское песо', country: 'Куба'),
    "CVE": Currency(code: "CVE",flag: SvgsFlags.capeVerde , symbol: '\$', title: 'Эскудо Кабо-Верде', country: 'Кабо-Верде'),
    "CZK": Currency(code: "CZK",flag: SvgsFlags.czechRepublic , symbol: 'Kč', title: 'Чешская крона', country: 'Чехия'),
    "DASH": Currency(code: "DASH", flag: SvgsFlags.dash, symbol: 'Đ',  title: 'Dash', country: 'Даш'),
    "DJF": Currency(code: "DJF",flag: SvgsFlags.djibouti  , symbol: '₣', title: 'Франк Джибути', country: 'Джибути'),
    "DKK": Currency(code: "DKK",flag: SvgsFlags.denmark, symbol: 'Kr', title: 'Датская крона', country: 'Дания'),
    "DOGE": Currency(code: "DOGE", flag: SvgsFlags.dogecoin, symbol: 'Ð',  title: 'Dogecoin', country: 'Dogecoin'),
    "DOP": Currency(code: "DOP",flag: SvgsFlags.dominicanRepublic  , symbol: 'Rd', title: 'Доминиканское песо', country: 'Доминиканская Республика'),
    "DZD": Currency(code: "DZD",flag: SvgsFlags.algeria  , symbol: 'Da', title: 'Алжирский динар', country: 'Алжир'),
    "EGP": Currency(code: "EGP",flag: SvgsFlags.egypt, symbol: 'Le', title: 'Египетский фунт', country: 'Египет'),
    "ERN": Currency(code: "ERN",flag: SvgsFlags.eritrea  , symbol: '	Nf', title: 'Накфа', country: 'Эритрея'),
    "ETB": Currency(code: "ETB" ,flag: SvgsFlags.ethiopia , symbol: 'Br', title: 'Эфиопский быр', country: 'Эфиопия'),
    "ETH": Currency(code: "ETH",flag: SvgsFlags.ethereum, symbol: 'Ξ',  title: 'Эфириум', country: 'Ethereum'),
    "EUR": Currency(code: "EUR",flag: SvgsFlags.europeanUnion  , symbol: '€', title: 'Евро', country: 'Европейский союз'),
    "FJD": Currency(code: "FJD",flag: SvgsFlags.fiji, symbol: '\$', title: 'Доллар Фиджи', country: 'Фиджи'),
    "FKP": Currency(code: "FKP",flag: SvgsFlags.falklandIslands  , symbol: '£', title: 'ФунтФолклендских островов', country: 'Фолклендские острова'),
    "GBP": Currency(code: "GBP",flag: SvgsFlags.unitedKingdom, symbol: '£', title: 'Фунт стерлингов', country: 'Великобритания'),
    "GEL": Currency(code: "GEL",flag: SvgsFlags.georgia  , symbol: '₾', title: 'Лари', country: 'Грузия'),
    "GGP": Currency(code: "GGP",flag: SvgsFlags.guernsey, symbol: '£',  title: 'Гернсийский фунт', country: 'Гернси'),
    "GHS": Currency(code: "GHS",flag: SvgsFlags.ghana  , symbol: '₵', title: 'Ганский седи', country: 'Гана'),
    "GIP": Currency(code: "GIP",flag: SvgsFlags.gibraltar  , symbol: '£', title: 'Гибралтарский фунт', country: 'Гибралтар'),
    "GMD": Currency(code: "GMD",flag: SvgsFlags.gambia  , symbol: 'D', title: 'Даласи', country: 'Гамбия'),
    "GNF": Currency(code: "GNF",flag: SvgsFlags.guinea  , symbol: '₣', title: 'Гвинейский франк', country: 'Гвинея'),
    "GTQ": Currency(code: "GTQ",flag: SvgsFlags.guatemala  , symbol: 'Q', title: 'Кетсаль', country: 'Гватемала'),
    "GYD": Currency(code: "GYD",flag: SvgsFlags.guyana  , symbol: '\$', title: 'Гайанский доллар', country: 'Гайана'),
    "HKD": Currency(code: "HKD",flag: SvgsFlags.hongKong  , symbol: '\$', title: 'Гонконгский доллар', country: 'Гонконг'),
    "HNL": Currency(code: "HNL",flag: SvgsFlags.honduras  , symbol: 'L', title: 'Лемпира', country: 'Гондурас'),
    "HRK": Currency(code: "HRK", flag:SvgsFlags.croatia , symbol: 'Kn', title: 'Хорватская куна', country: 'Хорватия'),
    "HTG": Currency(code: "HTG",flag: SvgsFlags.haiti  , symbol: 'G', title: 'Гурд', country: 'Гаити'),
    "HUF": Currency(code: "HUF",flag: SvgsFlags.hungary  , symbol: 'Ft', title: 'Форинт', country: 'Венгрия'),
    "IDR": Currency(code: "IDR",flag: SvgsFlags.indonesia  , symbol: 'Rp', title: 'Индонезийская рупия', country: 'Индонезия'),
    "ILS": Currency(code: "ILS",flag: SvgsFlags.israel  , symbol: '₪', title: 'Новый израильский шекель', country: 'Израиль'),
    "IMP": Currency(code: "IMP",flag: SvgsFlags.isleOfMan, symbol: '£',  title: 'Фунт Острова Мэн', country: 'Остров Мэн'),
    "INR": Currency(code: "INR",flag: SvgsFlags.india , symbol: '₹', title: 'Индийская рупия', country: 'Индия'),
    "IQD": Currency(code: "IQD",flag: SvgsFlags.iraq , symbol: 'Id', title: 'Иракский динар', country: 'Ирак'),
    "IRR": Currency(code: "IRR",flag: SvgsFlags.iran , symbol: 'Ie', title: 'Иранский риал', country: 'Иран'),
    "ISK": Currency(code: "ISK",flag: SvgsFlags.iceland , symbol: 'Kr', title: 'Исландская крона', country: 'Исландия'),
    "JEP": Currency(code: "JEP",flag: SvgsFlags.jersey , symbol: '£',  title: 'Джерсийский фунт', country: 'Джерси'),
    "JMD": Currency(code: "JMD",flag: SvgsFlags.jamaica , symbol: 'J\$', title: 'Ямайский доллар', country: 'Ямайка'),
    "JOD": Currency(code: "JOD",flag: SvgsFlags.jordan , symbol: 'Jd', title: 'Иорданский динар', country: 'Иордания'),
    "JPY": Currency(code: "JPY",flag: SvgsFlags.japan , symbol: '¥', title: 'Иена', country: 'Япония'),
    "KES": Currency(code: "KES",flag: SvgsFlags.kenya , symbol: '',  title: 'Кенийский шиллинг', country: 'Республика Кения'),
    "KGS": Currency(code: "KGS",flag: SvgsFlags.kyrgyzstan , symbol: 'C', title: 'Сом', country: 'Киргизия'),
    "KHR": Currency(code: "KHR",flag: SvgsFlags.cambodia, symbol: '៛', title: 'Риель', country: 'Камбоджа'),
    "KMF": Currency(code: "KMF",flag: SvgsFlags.comoros , symbol: '₣', title: 'Франк Комор', country: 'Коморы'),
    "KPW": Currency(code: "KPW",flag: SvgsFlags.northKorea , symbol: '₩', title: 'Северокорейская вона', country: 'КНДР'),
    "KRW": Currency(code: "KRW",flag: SvgsFlags.southKorea , symbol: '₩', title: 'Южнокорейская вона', country: 'Республика Корея'),
    "KWD": Currency(code: "KWD",flag: SvgsFlags.kuwait , symbol: 'Kd', title: 'Кувейтский динар', country: 'Кувейт'),
    "KYD": Currency(code: "KYD",flag: SvgsFlags.caymanIslands , symbol: '\$', title: 'Доллар Островов Кайман', country: 'Острова Кайман'),
    "KZT": Currency(code: "KZT",flag: SvgsFlags.kazakhstan , symbol: '₸', title: 'Тенге', country: 'Казахстан'),
    "LAK": Currency(code: "LAK",flag: SvgsFlags.laos , symbol: '₭', title: 'Кип', country: 'Лаос'),
    "LBP": Currency(code: "LBP",flag: SvgsFlags.lebanon , symbol: 'Lf', title: 'Ливанский фунт', country: 'Ливан'),
    "LD": Currency(code: "LD",flag: SvgsFlags.libya , symbol: '',  title: 'Ливийский динар', country: 'Ливия'), //TODO Search cur
    "LKR": Currency(code: "LKR",flag: SvgsFlags.sriLanka , symbol: 'Rs', title: 'Шри-ланкийская рупия', country: 'Шри-Ланка'),
    "LRD": Currency(code: "LRD",flag: SvgsFlags.liberia , symbol: 'L\$', title: 'Либерийский доллар', country: 'Либерия'),
    "LSL": Currency(code: "LSL",flag: SvgsFlags.lesotho , symbol: 'L', title: 'Лоти', country: 'Лесото'),
    // "LTC": Currency(code: "LTC",flag: SvgsFlags , symbol: '',  title: '', country: ''), //TODO Search cur
    "LYD": Currency(code: "LYD",flag: SvgsFlags.libya , symbol: 'Ld', title: 'Ливийский динар', country: 'Ливия'),
    "MAD": Currency(code: "MAD",flag: SvgsFlags.morocco , symbol: 'Dh', title: 'Марокканский дирхам', country: 'Марокко'),
    "MDL": Currency(code: "MDL",flag: SvgsFlags.moldova , symbol: 'L', title: 'Молдавский лей', country: 'Молдавия'),
    "MGA": Currency(code: "MGA",flag: SvgsFlags.madagascar , symbol: 'Ar', title: 'Малагасийский ариари', country: 'Мадагаскар'),
    "MKD": Currency(code: "MKD",flag: SvgsFlags.republicOfMacedonia , symbol: 'DEN', title: 'Денар', country: 'Северная Македония'),
    "MMK": Currency(code: "MMK", flag: SvgsFlags.myanmar, symbol: 'K', title: 'Кьят', country: 'Мьянма'),
    "MNT": Currency(code: "MNT",flag: SvgsFlags.mongolia, symbol: '₮', title: 'Тугрик', country: 'Монголия'),
    "MOP": Currency(code: "MOP",flag: SvgsFlags.macao, symbol: '\$', title: 'Патака', country: 'Макао'),
    // "MRO": Currency(code: "MRO",flag: Svgs , symbol: '',  title: '', country: ''), //TODO Search cur
    "MRU": Currency(code: "MRU",flag: SvgsFlags.mauritania, symbol: 'Um', title: 'Угия', country: 'Мавритания'),
    "MUR": Currency(code: "MUR",flag: SvgsFlags.mauritius, symbol: '₨', title: 'Маврикийская рупия', country: 'Маврикий'),
    "MVR": Currency(code: "MVR",flag: SvgsFlags.maldives, symbol: 'Rf', title: 'Руфия', country: 'Мальдивы'),
    "MWK": Currency(code: "MWK",flag: SvgsFlags.malawi, symbol: 'Mk', title: 'Квача', country: 'Малави'),
    "MXN": Currency(code: "MXN",flag: SvgsFlags.mexico, symbol: '\$', title: 'Мексиканское песо', country: 'Мексика'),
    "MYR": Currency(code: "MYR",flag: SvgsFlags.malaysia, symbol: 'Rm', title: 'Малайзийский ринггит', country: 'Малайзия'),
    "MZN": Currency(code: "MZN",flag: SvgsFlags.mozambique, symbol: 'Mt', title: 'Мозамбикский метикал', country: 'Мозамбик'),
    "NAD": Currency(code: "NAD",flag: SvgsFlags.namibia, symbol: 'N\$', title: 'Доллар Намибии', country: 'Намибия'),
    "NGN": Currency(code: "NGN",flag: SvgsFlags.nigeria, symbol: '₦', title: 'Найра', country: 'Нигерия'),
    "NIO": Currency(code: "NIO",flag: SvgsFlags.nicaragua, symbol: 'C\$', title: 'Золотая кордоба', country: 'Никарагуа'),
    "NOK": Currency(code: "NOK",flag: SvgsFlags.norway, symbol: 'Kr', title: 'Норвежская крона', country: 'Норвегия'),
    "NPR": Currency(code: "NPR",flag: SvgsFlags.nepal, symbol: 'N₨', title: 'Непальская рупия', country: 'Непал'),
    // "NXT": Currency(code: "NXT", symbol: '',  title: '', country: ''), //TODO Search cur
    "NZD": Currency(code: "NZD",flag: SvgsFlags.newZealand, symbol: '\$', title: 'Новозеландский доллар', country: 'Новая Зеландия'),
    "OMR": Currency(code: "OMR",flag: SvgsFlags.oman, symbol: 'Ro', title: 'Оманский риал', country: 'Оман'),
    "PAB": Currency(code: "PAB",flag: SvgsFlags.panama, symbol: 'B/', title: 'Бальбоа', country: 'Панама'),
    "PEN": Currency(code: "PEN",flag: SvgsFlags.peru, symbol: 'S/', title: 'Новый соль', country: 'Перу'),
    "PGK": Currency(code: "PGK",flag: SvgsFlags.papuaNewGuinea, symbol: 'K', title: 'Кина', country: 'Папуа — Новая Гвинея'),
    "PHP": Currency(code: "PHP",flag: SvgsFlags.philippines, symbol: '₱', title: 'Филиппинское песо', country: 'Филиппины'),
    "PKR": Currency(code: "PKR",flag: SvgsFlags.pakistan , symbol: 'Re', title: 'Пакистанская рупия', country: 'Пакистан'),
    "PLN": Currency(code: "PLN",flag: SvgsFlags.poland , symbol: 'Zł', title: 'Злотый', country: 'Польша'),
    "PYG": Currency(code: "PYG",flag: SvgsFlags.paraguay , symbol: '₲', title: 'Гуарани', country: 'Парагвай'),
    "QAR": Currency(code: "QAR",flag: SvgsFlags.qatar , symbol: '﷼', title: 'Катарский риал', country: 'Катар'),
    "RON": Currency(code: "RON",flag: SvgsFlags.romania , symbol: 'L', title: 'Румынский лей', country: 'Румыния'),
    "RSD": Currency(code: "RSD",flag: SvgsFlags.serbia , symbol: 'Di', title: 'Сербский динар', country: 'Сербия'),
    "RUB": Currency(code: "RUB", flag: SvgsFlags.russia, symbol: '₽',  title: 'Российский рубль', country: 'Россия'),
    "RWF": Currency(code: "RWF",flag: SvgsFlags.rwanda , symbol: '₣', title: 'Франк Руанды', country: 'Руанда'),
    "SAR": Currency(code: "SAR",flag: SvgsFlags.saudiArabia , symbol: '﷼', title: 'Саудовский риял', country: 'Саудовская Аравия'),
    "SBD": Currency(code: "SBD",flag: SvgsFlags.solomonIslands , symbol: '\$', title: 'Доллар Соломоновых Островов', country: 'Соломоновы Острова'),
    "SCR": Currency(code: "SCR",flag: SvgsFlags.seychelles , symbol: 'Re', title: 'Сейшельская рупия', country: 'Сейшельские Острова'),
    "SDG": Currency(code: "SDG",flag: SvgsFlags.sudan , symbol: '£', title: 'Суданский фунт', country: 'Судан'),
    "SEK": Currency(code: "SEK",flag: SvgsFlags.sweden , symbol: 'Kr', title: 'Шведская крона', country: 'Швеция'),
    "SGD": Currency(code: "SGD",flag: SvgsFlags.singapore , symbol: '\$', title: 'Сингапурский доллар', country: 'Сингапур'),
    "SHP": Currency(code: "SHP",flag: SvgsFlags.unitedKingdom , symbol: '£', title: 'Фунт Святой Елены', country: 'Остров Святой ЕленыОстров ВознесенияТристан-да-Кунья'),
    "SLL": Currency(code: "SLL",flag: SvgsFlags.sierraLeone , symbol: 'Le', title: 'Леоне', country: 'Сьерра-Леоне'),
    "SOS": Currency(code: "SOS",flag: SvgsFlags.somalia , symbol: 'S', title: 'Сомалийский шиллинг', country: 'Сомали'),
    "SRD": Currency(code: "SRD",flag: SvgsFlags.suriname , symbol: '\$', title: 'Суринамский доллар', country: 'Суринам'),
    "SSP": Currency(code: "SSP",flag: SvgsFlags.southSudan , symbol: 'Db', title: 'Южносуданский фунт', country: 'Южный Судан'),
    "STN": Currency(code: "STN",flag: SvgsFlags.saoTomeAndPrince , symbol: 'Db', title: 'Добра', country: 'Сан-Томе и Принсипи'),
    "SVC": Currency(code: "SVC",flag: SvgsFlags.elSalvador , symbol: '₡', title: 'Сальвадорский колон', country: 'Сальвадор'),
    "SYP": Currency(code: "SYP",flag: SvgsFlags.syria , symbol: 'Ls', title: 'Сирийский фунт', country: 'Сирия'),
    "SZL": Currency(code: "SZL",flag: SvgsFlags.swaziland , symbol: 'L', title: 'Мн. Эмалангени', country: 'Эсватини'),
    "THB": Currency(code: "THB",flag: SvgsFlags.thailand , symbol: '฿', title: 'Бат', country: 'Таиланд'),
    "TJS": Currency(code: "TJS",flag: SvgsFlags.tajikistan , symbol: 'Sm', title: 'Сомони', country: 'Таджикистан'),
    "TMT": Currency(code: "TMT",flag: SvgsFlags.turkmenistan , symbol: 'T', title: 'Новый туркменский манат', country: 'Туркмения'),
    "TND": Currency(code: "TND",flag: SvgsFlags.tunisia , symbol: 'Dt', title: 'Тунисский динар', country: 'Тунис'),
    "TOP": Currency(code: "TOP",flag: SvgsFlags.tonga , symbol: '\$', title: 'Паанга', country: 'Тонга'),
    "TRY": Currency(code: "TRY",flag: SvgsFlags.turkey , symbol: '₺', title: 'Турецкая лира', country: 'Турция'),
    "TTD": Currency(code: "TTD",flag: SvgsFlags.trinidadAndTobago , symbol: '\$', title: 'Доллар Тринидада и Тобаго', country: 'Тринидад и Тобаго'),
    "TWD": Currency(code: "TWD",flag: SvgsFlags.taiwan , symbol: 'Nt', title: 'Новый тайваньский доллар', country: 'Тайвань'),
    "TZS": Currency(code: "TZS",flag: SvgsFlags.tanzania , symbol: 'Sh', title: 'Танзанийский шиллинг', country: 'Танзания'),
    "UAH": Currency(code: "UAH",flag: SvgsFlags.ukraine , symbol: '₴', title: 'Гривна', country: 'Украина'),
    "UGX": Currency(code: "UGX",flag: SvgsFlags.uganda , symbol: 'Sh', title: 'Угандийский шиллинг', country: 'Уганда'),
    "USD": Currency(code: "USD",  flag: SvgsFlags.unitedStates, symbol: '\$', title: 'Доллар', country: 'Америка'),
    "UYU": Currency(code: "UYU",flag: SvgsFlags.uruguay , symbol: '\$', title: 'Уругвайское песо', country: 'Уругвай'),
    "UZS": Currency(code: "UZS",flag: SvgsFlags.uzbekistan , symbol: 'So', title: 'Узбекский сум', country: 'Узбекистан'),
    // "VEF_BLKMKT": Currency(code: "VEF_BLKMKT", symbol: '',  title: '', country: ''), //TODO Search cur
    // "VEF_DICOM": Currency(code: "VEF_DICOM", symbol: '',  title: '', country: ''), //TODO Search cur
    // "VEF_DIPRO": Currency(code: "VEF_DIPRO", symbol: '',  title: '', country: ''), //TODO Search cur
    "VES": Currency(code: "VES",flag: SvgsFlags.venezuela , symbol: 'Bs', title: 'Суверенный боливар', country: 'Венесуэла'),
    "VND": Currency(code: "VND",flag: SvgsFlags.vietnam , symbol: '₫', title: 'Донг', country: 'Вьетнам'),
    "VUV": Currency(code: "VUV",flag: SvgsFlags.vanuatu , symbol: 'Vt', title: 'Вату', country: 'Вануату'),
    "WST": Currency(code: "WST",flag: SvgsFlags.samoa , symbol: '\$', title: 'Тала', country: 'Самоа'),
    "XAF": Currency(code: "XAF",flag: SvgsFlags.republicOfTheCongo , symbol: '₣', title: 'Франк КФА BEAC', country: 'Республика Конго'),
    // "XAG": Currency(code: "XAG", symbol: '',  title: '', country: ''), //TODO Search cur
    // "XAU": Currency(code: "XAU", symbol: '',  title: '', country: ''), //TODO Search cur
    "XCD": Currency(code: "XCD",flag: SvgsFlags.anguilla , symbol: '\$', title: 'Восточно-карибский доллар', country: 'Ангилья'),
    // "XDR": Currency(code: "XDR", symbol: '',  title: '', country: ''), //TODO Search cur
    // "XMR": Currency(code: "XMR", symbol: '',  title: '', country: ''), //TODO Search cur
    "XOF": Currency(code: "XOF",flag: SvgsFlags.senegal , symbol: '₣', title: 'Франк КФА', country: 'Сенегал'),
    // "XPD": Currency(code: "XPD", symbol: '',  title: '', country: ''), //TODO Search cur
    "XPF": Currency(code: "XPF",flag: SvgsFlags.frenchPolynesia , symbol: '₣', title: 'Франк КФП', country: 'Французская Полинезия'),
    // "XPT": Currency(code: "XPT", symbol: '',  title: '', country: ''), //TODO Search cur
    // "XRP": Currency(code: "XRP", symbol: '',  title: '', country: ''), //TODO Search cur
    "YER": Currency(code: "YER",flag: SvgsFlags.yemen , symbol: '﷼', title: 'Йеменский риал', country: 'Йемен'),
    "ZAR": Currency(code: "ZAR",flag: SvgsFlags.southAfrica , symbol: 'R', title: 'Рэнд', country: 'ЮАР'),
    "ZMW": Currency(code: "ZMW",flag: SvgsFlags.zambia , symbol: 'K', title: 'Замбийская квача', country: 'Замбия'),
    "ZWL": Currency(code: "ZWL",flag: SvgsFlags.zimbabwe , symbol: 'Z\$', title: 'Доллар Зимбабве', country: 'Зимбабве'),
    // "NMC": Currency(code: "NMC", symbol: '',  title: '', country: ''), //TODO Search cur
    // "PPC": Currency(code: "PPC", symbol: '',  title: '', country: ''), //TODO Search cur
    // "NVC": Currency(code: "NVC", symbol: '',  title: '', country: ''), //TODO Search cur
    // "XPM": Currency(code: "XPM", symbol: '',  title: '', country: ''), //TODO Search cur
    // "EAC": Currency(code: "EAC", symbol: '',  title: '', country: ''), //TODO Search cur
    // "VTC": Currency(code: "VTC", symbol: '',  title: '', country: ''), //TODO Search cur
    // "EMC": Currency(code: "EMC", symbol: '',  title: '', country: ''), //TODO Search cur
    // "FCT": Currency(code: "FCT", symbol: '',  title: '', country: ''), //TODO Search cur
    // "BNB": Currency(code: "BNB", symbol: '',  title: '', country: ''), //TODO Search cur
  };
}
