import 'currency.dart';

class CurrenciesList {
  static final currenciesList = <String, Currency>{
    // "AED": CurrencyCard(code: "AED", symbol: '', icon: '', title: ''),
    // "AFN": CurrencyCard(code: "AFN", symbol: '', icon: '', title: ''),
    // "ALL": CurrencyCard(code: "ALL", symbol: '', icon: '', title: ''),
    // "AMD": CurrencyCard(code: "AMD", symbol: '', icon: '', title: ''),
    // "ANG": CurrencyCard(code: "ANG", symbol: '', icon: '', title: ''),
    // "AOA": CurrencyCard(code: "AOA", symbol: '', icon: '', title: ''),
    // "ARS": CurrencyCard(code: "ARS", symbol: '', icon: '', title: ''),
    // "AUD": CurrencyCard(code: "AUD", symbol: '', icon: '', title: ''),
    // "AWG": CurrencyCard(code: "AWG", symbol: '', icon: '', title: ''),
    // "AZN": CurrencyCard(code: "AZN", symbol: '', icon: '', title: ''),
    // "BAM": CurrencyCard(code: "BAM", symbol: '', icon: '', title: ''),
    // "BBD": CurrencyCard(code: "BBD", symbol: '', icon: '', title: ''),
    // "BDT": CurrencyCard(code: "BDT", symbol: '', icon: '', title: ''),
    // "BGN": CurrencyCard(code: "BGN", symbol: '', icon: '', title: ''),
    // "BHD": CurrencyCard(code: "BHD", symbol: '', icon: '', title: ''),
    // "BIF": CurrencyCard(code: "BIF", symbol: '', icon: '', title: ''),
    // "BMD": CurrencyCard(code: "BMD", symbol: '', icon: '', title: ''),
    // "BND": CurrencyCard(code: "BND", symbol: '', icon: '', title: ''),
    // "BOB": CurrencyCard(code: "BOB", symbol: '', icon: '', title: ''),
    // "BRL": CurrencyCard(code: "BRL", symbol: '', icon: '', title: ''),
    // "BSD": CurrencyCard(code: "BSD", symbol: '', icon: '', title: ''),
    // "BTC": CurrencyCard(code: "BTC", symbol: '', icon: '', title: ''),
    // "BTN": CurrencyCard(code: "BTN", symbol: '', icon: '', title: ''),
    // "BTS": CurrencyCard(code: "BTS", symbol: '', icon: '', title: ''),
    // "BWP": CurrencyCard(code: "BWP", symbol: '', icon: '', title: ''),
    // "BYN": CurrencyCard(code: "BYN", symbol: '', icon: '', title: ''),
    // "BZD": CurrencyCard(code: "BZD", symbol: '', icon: '', title: ''),
    // "CAD": CurrencyCard(code: "CAD", symbol: '', icon: '', title: ''),
    // "CDF": CurrencyCard(code: "CDF", symbol: '', icon: '', title: ''),
    // "CHF": CurrencyCard(code: "CHF", symbol: '', icon: '', title: ''),
    // "CLF": CurrencyCard(code: "CLF", symbol: '', icon: '', title: ''),
    // "CLP": CurrencyCard(code: "CLP", symbol: '', icon: '', title: ''),
    // "CNH": CurrencyCard(code: "CNH", symbol: '', icon: '', title: ''),
    "CNY": Currency(
      code: "CNY",
      symbol: '¥',
      icon: '🇨🇳',
      title: 'Китайский йен',
      rate: 6.3651,
      isEnable: false,
    ),
    // "COP": CurrencyCard(code: "COP", symbol: '', icon: '', title: ''),
    // "CRC": CurrencyCard(code: "CRC", symbol: '', icon: '', title: ''),
    // "CUC": CurrencyCard(code: "CUC", symbol: '', icon: '', title: ''),
    // "CUP": CurrencyCard(code: "CUP", symbol: '', icon: '', title: ''),
    // "CVE": CurrencyCard(code: "CVE", symbol: '', icon: '', title: ''),
    // "CZK": CurrencyCard(code: "CZK", symbol: '', icon: '', title: ''),
    // "DASH": CurrencyCard(code: "DASH", symbol: '', icon: '', title: ''),
    // "DJF": CurrencyCard(code: "DJF", symbol: '', icon: '', title: ''),
    // "DKK": CurrencyCard(code: "DKK", symbol: '', icon: '', title: ''),
    // "DOGE": CurrencyCard(code: "DOGE", symbol: '', icon: '', title: ''),
    // "DOP": CurrencyCard(code: "DOP", symbol: '', icon: '', title: ''),
    // "DZD": CurrencyCard(code: "DZD", symbol: '', icon: '', title: ''),
    // "EGP": CurrencyCard(code: "EGP", symbol: '', icon: '', title: ''),
    // "ERN": CurrencyCard(code: "ERN", symbol: '', icon: '', title: ''),
    // "ETB": CurrencyCard(code: "ETB", symbol: '', icon: '', title: ''),
    // "ETH": CurrencyCard(code: "ETH", symbol: '', icon: '', title: ''),
    "EUR": Currency(
      code: "EUR",
      symbol: '€',
      icon: '🇪🇺',
      title: 'Евро',
      rate: 0.919413,
      isEnable: false,
    ),
    // "FJD": CurrencyCard(code: "FJD", symbol: '', icon: '', title: ''),
    // "FKP": CurrencyCard(code: "FKP", symbol: '', icon: '', title: ''),
    // "GBP": CurrencyCard(code: "GBP", symbol: '', icon: '', title: ''),
    // "GEL": CurrencyCard(code: "GEL", symbol: '', icon: '', title: ''),
    // "GGP": CurrencyCard(code: "GGP", symbol: '', icon: '', title: ''),
    // "GHS": CurrencyCard(code: "GHS", symbol: '', icon: '', title: ''),
    // "GIP": CurrencyCard(code: "GIP", symbol: '', icon: '', title: ''),
    // "GMD": CurrencyCard(code: "GMD", symbol: '', icon: '', title: ''),
    // "GNF": CurrencyCard(code: "GNF", symbol: '', icon: '', title: ''),
    // "GTQ": CurrencyCard(code: "GTQ", symbol: '', icon: '', title: ''),
    // "GYD": CurrencyCard(code: "GYD", symbol: '', icon: '', title: ''),
    // "HKD": CurrencyCard(code: "HKD", symbol: '', icon: '', title: ''),
    // "HNL": CurrencyCard(code: "HNL", symbol: '', icon: '', title: ''),
    // "HRK": CurrencyCard(code: "HRK", symbol: '', icon: '', title: ''),
    // "HTG": CurrencyCard(code: "HTG", symbol: '', icon: '', title: ''),
    // "HUF": CurrencyCard(code: "HUF", symbol: '', icon: '', title: ''),
    // "IDR": CurrencyCard(code: "IDR", symbol: '', icon: '', title: ''),
    // "ILS": CurrencyCard(code: "ILS", symbol: '', icon: '', title: ''),
    // "IMP": CurrencyCard(code: "IMP", symbol: '', icon: '', title: ''),
    // "INR": CurrencyCard(code: "INR", symbol: '', icon: '', title: ''),
    // "IQD": CurrencyCard(code: "IQD", symbol: '', icon: '', title: ''),
    // "IRR": CurrencyCard(code: "IRR", symbol: '', icon: '', title: ''),
    // "ISK": CurrencyCard(code: "ISK", symbol: '', icon: '', title: ''),
    // "JEP": CurrencyCard(code: "JEP", symbol: '', icon: '', title: ''),
    // "JMD": CurrencyCard(code: "JMD", symbol: '', icon: '', title: ''),
    // "JOD": CurrencyCard(code: "JOD", symbol: '', icon: '', title: ''),
    // "JPY": CurrencyCard(code: "JPY", symbol: '', icon: '', title: ''),
    // "KES": CurrencyCard(code: "KES", symbol: '', icon: '', title: ''),
    // "KGS": CurrencyCard(code: "KGS", symbol: '', icon: '', title: ''),
    // "KHR": CurrencyCard(code: "KHR", symbol: '', icon: '', title: ''),
    // "KMF": CurrencyCard(code: "KMF", symbol: '', icon: '', title: ''),
    // "KPW": CurrencyCard(code: "KPW", symbol: '', icon: '', title: ''),
    // "KRW": CurrencyCard(code: "KRW", symbol: '', icon: '', title: ''),
    // "KWD": CurrencyCard(code: "KWD", symbol: '', icon: '', title: ''),
    // "KYD": CurrencyCard(code: "KYD", symbol: '', icon: '', title: ''),
    // "KZT": CurrencyCard(code: "KZT", symbol: '', icon: '', title: ''),
    // "LAK": CurrencyCard(code: "LAK", symbol: '', icon: '', title: ''),
    // "LBP": CurrencyCard(code: "LBP", symbol: '', icon: '', title: ''),
    // "LD": CurrencyCard(code: "LD", symbol: '', icon: '', title: ''),
    // "LKR": CurrencyCard(code: "LKR", symbol: '', icon: '', title: ''),
    // "LRD": CurrencyCard(code: "LRD", symbol: '', icon: '', title: ''),
    // "LSL": CurrencyCard(code: "LSL", symbol: '', icon: '', title: ''),
    // "LTC": CurrencyCard(code: "LTC", symbol: '', icon: '', title: ''),
    // "LYD": CurrencyCard(code: "LYD", symbol: '', icon: '', title: ''),
    // "MAD": CurrencyCard(code: "MAD", symbol: '', icon: '', title: ''),
    // "MDL": CurrencyCard(code: "MDL", symbol: '', icon: '', title: ''),
    // "MGA": CurrencyCard(code: "MGA", symbol: '', icon: '', title: ''),
    // "MKD": CurrencyCard(code: "MKD", symbol: '', icon: '', title: ''),
    // "MMK": CurrencyCard(code: "MMK", symbol: '', icon: '', title: ''),
    // "MNT": CurrencyCard(code: "MNT", symbol: '', icon: '', title: ''),
    // "MOP": CurrencyCard(code: "MOP", symbol: '', icon: '', title: ''),
    // "MRO": CurrencyCard(code: "MRO", symbol: '', icon: '', title: ''),
    // "MRU": CurrencyCard(code: "MRU", symbol: '', icon: '', title: ''),
    // "MUR": CurrencyCard(code: "MUR", symbol: '', icon: '', title: ''),
    // "MVR": CurrencyCard(code: "MVR", symbol: '', icon: '', title: ''),
    // "MWK": CurrencyCard(code: "MWK", symbol: '', icon: '', title: ''),
    // "MXN": CurrencyCard(code: "MXN", symbol: '', icon: '', title: ''),
    // "MYR": CurrencyCard(code: "MYR", symbol: '', icon: '', title: ''),
    // "MZN": CurrencyCard(code: "MZN", symbol: '', icon: '', title: ''),
    // "NAD": CurrencyCard(code: "NAD", symbol: '', icon: '', title: ''),
    // "NGN": CurrencyCard(code: "NGN", symbol: '', icon: '', title: ''),
    // "NIO": CurrencyCard(code: "NIO", symbol: '', icon: '', title: ''),
    // "NOK": CurrencyCard(code: "NOK", symbol: '', icon: '', title: ''),
    // "NPR": CurrencyCard(code: "NPR", symbol: '', icon: '', title: ''),
    // "NXT": CurrencyCard(code: "NXT", symbol: '', icon: '', title: ''),
    // "NZD": CurrencyCard(code: "NZD", symbol: '', icon: '', title: ''),
    // "OMR": CurrencyCard(code: "OMR", symbol: '', icon: '', title: ''),
    // "PAB": CurrencyCard(code: "PAB", symbol: '', icon: '', title: ''),
    // "PEN": CurrencyCard(code: "PEN", symbol: '', icon: '', title: ''),
    // "PGK": CurrencyCard(code: "PGK", symbol: '', icon: '', title: ''),
    // "PHP": CurrencyCard(code: "PHP", symbol: '', icon: '', title: ''),
    // "PKR": CurrencyCard(code: "PKR", symbol: '', icon: '', title: ''),
    // "PLN": CurrencyCard(code: "PLN", symbol: '', icon: '', title: ''),
    // "PYG": CurrencyCard(code: "PYG", symbol: '', icon: '', title: ''),
    // "QAR": CurrencyCard(code: "QAR", symbol: '', icon: '', title: ''),
    // "RON": CurrencyCard(code: "RON", symbol: '', icon: '', title: ''),
    // "RSD": CurrencyCard(code: "RSD", symbol: '', icon: '', title: ''),
    "RUB": Currency(
      code: "RUB",
      symbol: '₽',
      icon: '🇷🇺',
      title: 'Российский рубль',
      rate: 80.850086,
      isEnable: false,
    ),
    // "RWF": CurrencyCard(code: "RWF", symbol: '', icon: '', title: ''),
    // "SAR": CurrencyCard(code: "SAR", symbol: '', icon: '', title: ''),
    // "SBD": CurrencyCard(code: "SBD", symbol: '', icon: '', title: ''),
    // "SCR": CurrencyCard(code: "SCR", symbol: '', icon: '', title: ''),
    // "SDG": CurrencyCard(code: "SDG", symbol: '', icon: '', title: ''),
    // "SEK": CurrencyCard(code: "SEK", symbol: '', icon: '', title: ''),
    // "SGD": CurrencyCard(code: "SGD", symbol: '', icon: '', title: ''),
    // "SHP": CurrencyCard(code: "SHP", symbol: '', icon: '', title: ''),
    // "SLL": CurrencyCard(code: "SLL", symbol: '', icon: '', title: ''),
    // "SOS": CurrencyCard(code: "SOS", symbol: '', icon: '', title: ''),
    // "SRD": CurrencyCard(code: "SRD", symbol: '', icon: '', title: ''),
    // "SSP": CurrencyCard(code: "SSP", symbol: '', icon: '', title: ''),
    // "STD": CurrencyCard(code: "STD", symbol: '', icon: '', title: ''),
    // "STN": CurrencyCard(code: "STN", symbol: '', icon: '', title: ''),
    // "STR": CurrencyCard(code: "STR", symbol: '', icon: '', title: ''),
    // "SVC": CurrencyCard(code: "SVC", symbol: '', icon: '', title: ''),
    // "SYP": CurrencyCard(code: "SYP", symbol: '', icon: '', title: ''),
    // "SZL": CurrencyCard(code: "SZL", symbol: '', icon: '', title: ''),
    // "THB": CurrencyCard(code: "THB", symbol: '', icon: '', title: ''),
    // "TJS": CurrencyCard(code: "TJS", symbol: '', icon: '', title: ''),
    // "TMT": CurrencyCard(code: "TMT", symbol: '', icon: '', title: ''),
    // "TND": CurrencyCard(code: "TND", symbol: '', icon: '', title: ''),
    // "TOP": CurrencyCard(code: "TOP", symbol: '', icon: '', title: ''),
    // "TRY": CurrencyCard(code: "TRY", symbol: '', icon: '', title: ''),
    // "TTD": CurrencyCard(code: "TTD", symbol: '', icon: '', title: ''),
    // "TWD": CurrencyCard(code: "TWD", symbol: '', icon: '', title: ''),
    // "TZS": CurrencyCard(code: "TZS", symbol: '', icon: '', title: ''),
    // "UAH": CurrencyCard(code: "UAH", symbol: '', icon: '', title: ''),
    // "UGX": CurrencyCard(code: "UGX", symbol: '', icon: '', title: ''),
    "USD": Currency(
      code: "USD",
      symbol: '\$',
      icon: '🇺🇸',
      title: 'Доллар',
      rate: 1,
      isEnable: false,
    ),
    // "UYU": CurrencyCard(code: "UYU", symbol: '', icon: '', title: ''),
    // "UZS": CurrencyCard(code: "UZS", symbol: '', icon: '', title: ''),
    // "VEF_BLKMKT": CurrencyCard(code: "VEF_BLKMKT", symbol: '', icon: '', title: ''),
    // "VEF_DICOM": CurrencyCard(code: "VEF_DICOM", symbol: '', icon: '', title: ''),
    // "VEF_DIPRO": CurrencyCard(code: "VEF_DIPRO", symbol: '', icon: '', title: ''),
    // "VES": CurrencyCard(code: "VES", symbol: '', icon: '', title: ''),
    // "VND": CurrencyCard(code: "VND", symbol: '', icon: '', title: ''),
    // "VUV": CurrencyCard(code: "VUV", symbol: '', icon: '', title: ''),
    // "WST": CurrencyCard(code: "WST", symbol: '', icon: '', title: ''),
    // "XAF": CurrencyCard(code: "XAF", symbol: '', icon: '', title: ''),
    // "XAG": CurrencyCard(code: "XAG", symbol: '', icon: '', title: ''),
    // "XAU": CurrencyCard(code: "XAU", symbol: '', icon: '', title: ''),
    // "XCD": CurrencyCard(code: "XCD", symbol: '', icon: '', title: ''),
    // "XDR": CurrencyCard(code: "XDR", symbol: '', icon: '', title: ''),
    // "XMR": CurrencyCard(code: "XMR", symbol: '', icon: '', title: ''),
    // "XOF": CurrencyCard(code: "XOF", symbol: '', icon: '', title: ''),
    // "XPD": CurrencyCard(code: "XPD", symbol: '', icon: '', title: ''),
    // "XPF": CurrencyCard(code: "XPF", symbol: '', icon: '', title: ''),
    // "XPT": CurrencyCard(code: "XPT", symbol: '', icon: '', title: ''),
    // "XRP": CurrencyCard(code: "XRP", symbol: '', icon: '', title: ''),
    // "YER": CurrencyCard(code: "YER", symbol: '', icon: '', title: ''),
    // "ZAR": CurrencyCard(code: "ZAR", symbol: '', icon: '', title: ''),
    // "ZMW": CurrencyCard(code: "ZMW", symbol: '', icon: '', title: ''),
    // "ZWL": CurrencyCard(code: "ZWL", symbol: '', icon: '', title: ''),
    // "NMC": CurrencyCard(code: "NMC", symbol: '', icon: '', title: ''),
    // "PPC": CurrencyCard(code: "PPC", symbol: '', icon: '', title: ''),
    // "NVC": CurrencyCard(code: "NVC", symbol: '', icon: '', title: ''),
    // "XPM": CurrencyCard(code: "XPM", symbol: '', icon: '', title: ''),
    // "EAC": CurrencyCard(code: "EAC", symbol: '', icon: '', title: ''),
    // "VTC": CurrencyCard(code: "VTC", symbol: '', icon: '', title: ''),
    // "EMC": CurrencyCard(code: "EMC", symbol: '', icon: '', title: ''),
    // "FCT": CurrencyCard(code: "FCT", symbol: '', icon: '', title: ''),
    // "BNB": CurrencyCard(code: "BNB", symbol: '', icon: '', title: ''),
  };
}
