import '../api/api_client.dart';
import 'currency.dart';

class CurrenciesList {
  Future<Map<String, dynamic>> getRateList() async {
    Map<String, dynamic> rates = await ApiClient().get();
    return rates['rates'];
  }

  static final currenciesList = <String, Currency>{
    "AED": Currency(code: "AED", symbol: '', icon: '', title: 'Дирхам ОАЭ'),
    "AFN": Currency(code: "AFN", symbol: '', icon: '', title: 'Афганский афгани'),
    "ALL": Currency(code: "ALL", symbol: '', icon: '', title: ''),
    "AMD": Currency(code: "AMD", symbol: '', icon: '', title: ''),
    "ANG": Currency(code: "ANG", symbol: '', icon: '', title: ''),
    "AOA": Currency(code: "AOA", symbol: '', icon: '', title: ''),
    "ARS": Currency(code: "ARS", symbol: '', icon: '', title: ''),
    "AUD": Currency(code: "AUD", symbol: '', icon: '', title: ''),
    "AWG": Currency(code: "AWG", symbol: '', icon: '', title: ''),
    "AZN": Currency(code: "AZN", symbol: '', icon: '', title: ''),
    "BAM": Currency(code: "BAM", symbol: '', icon: '', title: ''),
    "BBD": Currency(code: "BBD", symbol: '', icon: '', title: ''),
    "BDT": Currency(code: "BDT", symbol: '', icon: '', title: ''),
    "BGN": Currency(code: "BGN", symbol: '', icon: '', title: ''),
    "BHD": Currency(code: "BHD", symbol: '', icon: '', title: ''),
    "BIF": Currency(code: "BIF", symbol: '', icon: '', title: ''),
    "BMD": Currency(code: "BMD", symbol: '', icon: '', title: ''),
    "BND": Currency(code: "BND", symbol: '', icon: '', title: ''),
    "BOB": Currency(code: "BOB", symbol: '', icon: '', title: ''),
    "BRL": Currency(code: "BRL", symbol: '', icon: '', title: ''),
    "BSD": Currency(code: "BSD", symbol: '', icon: '', title: ''),
    "BTC": Currency(code: "BTC", symbol: '', icon: '', title: ''),
    "BTN": Currency(code: "BTN", symbol: '', icon: '', title: ''),
    "BTS": Currency(code: "BTS", symbol: '', icon: '', title: ''),
    "BWP": Currency(code: "BWP", symbol: '', icon: '', title: ''),
    "BYN": Currency(code: "BYN", symbol: '', icon: '', title: ''),
    "BZD": Currency(code: "BZD", symbol: '', icon: '', title: ''),
    "CAD": Currency(code: "CAD", symbol: '', icon: '', title: ''),
    "CDF": Currency(code: "CDF", symbol: '', icon: '', title: ''),
    "CHF": Currency(code: "CHF", symbol: '', icon: '', title: ''),
    "CLF": Currency(code: "CLF", symbol: '', icon: '', title: ''),
    "CLP": Currency(code: "CLP", symbol: '', icon: '', title: ''),
    "CNH": Currency(code: "CNH", symbol: '', icon: '', title: ''),
    "CNY": Currency(
      code: "CNY",
      symbol: '¥',
      icon: '🇨🇳',
      title: 'Китайский йен',
      rate: 0,
      isEnable: false,
    ),
    // "COP": Currency(code: "COP", symbol: '', icon: '', title: ''),
    // "CRC": Currency(code: "CRC", symbol: '', icon: '', title: ''),
    // "CUC": Currency(code: "CUC", symbol: '', icon: '', title: ''),
    // "CUP": Currency(code: "CUP", symbol: '', icon: '', title: ''),
    // "CVE": Currency(code: "CVE", symbol: '', icon: '', title: ''),
    // "CZK": Currency(code: "CZK", symbol: '', icon: '', title: ''),
    // "DASH": Currency(code: "DASH", symbol: '', icon: '', title: ''),
    // "DJF": Currency(code: "DJF", symbol: '', icon: '', title: ''),
    // "DKK": Currency(code: "DKK", symbol: '', icon: '', title: ''),
    // "DOGE": Currency(code: "DOGE", symbol: '', icon: '', title: ''),
    // "DOP": Currency(code: "DOP", symbol: '', icon: '', title: ''),
    // "DZD": Currency(code: "DZD", symbol: '', icon: '', title: ''),
    // "EGP": Currency(code: "EGP", symbol: '', icon: '', title: ''),
    // "ERN": Currency(code: "ERN", symbol: '', icon: '', title: ''),
    // "ETB": Currency(code: "ETB", symbol: '', icon: '', title: ''),
    // "ETH": Currency(code: "ETH", symbol: '', icon: '', title: ''),
    "EUR": Currency(
      code: "EUR",
      symbol: '€',
      icon: '🇪🇺',
      title: 'Евро',
      rate: 0,
      isEnable: false,
    ),
    // "FJD": Currency(code: "FJD", symbol: '', icon: '', title: ''),
    // "FKP": Currency(code: "FKP", symbol: '', icon: '', title: ''),
    // "GBP": Currency(code: "GBP", symbol: '', icon: '', title: ''),
    // "GEL": Currency(code: "GEL", symbol: '', icon: '', title: ''),
    // "GGP": Currency(code: "GGP", symbol: '', icon: '', title: ''),
    // "GHS": Currency(code: "GHS", symbol: '', icon: '', title: ''),
    // "GIP": Currency(code: "GIP", symbol: '', icon: '', title: ''),
    // "GMD": Currency(code: "GMD", symbol: '', icon: '', title: ''),
    // "GNF": Currency(code: "GNF", symbol: '', icon: '', title: ''),
    // "GTQ": Currency(code: "GTQ", symbol: '', icon: '', title: ''),
    // "GYD": Currency(code: "GYD", symbol: '', icon: '', title: ''),
    // "HKD": Currency(code: "HKD", symbol: '', icon: '', title: ''),
    // "HNL": Currency(code: "HNL", symbol: '', icon: '', title: ''),
    // "HRK": Currency(code: "HRK", symbol: '', icon: '', title: ''),
    // "HTG": Currency(code: "HTG", symbol: '', icon: '', title: ''),
    // "HUF": Currency(code: "HUF", symbol: '', icon: '', title: ''),
    // "IDR": Currency(code: "IDR", symbol: '', icon: '', title: ''),
    // "ILS": Currency(code: "ILS", symbol: '', icon: '', title: ''),
    // "IMP": Currency(code: "IMP", symbol: '', icon: '', title: ''),
    // "INR": Currency(code: "INR", symbol: '', icon: '', title: ''),
    // "IQD": Currency(code: "IQD", symbol: '', icon: '', title: ''),
    // "IRR": Currency(code: "IRR", symbol: '', icon: '', title: ''),
    // "ISK": Currency(code: "ISK", symbol: '', icon: '', title: ''),
    // "JEP": Currency(code: "JEP", symbol: '', icon: '', title: ''),
    // "JMD": Currency(code: "JMD", symbol: '', icon: '', title: ''),
    // "JOD": Currency(code: "JOD", symbol: '', icon: '', title: ''),
    // "JPY": Currency(code: "JPY", symbol: '', icon: '', title: ''),
    // "KES": Currency(code: "KES", symbol: '', icon: '', title: ''),
    // "KGS": Currency(code: "KGS", symbol: '', icon: '', title: ''),
    // "KHR": Currency(code: "KHR", symbol: '', icon: '', title: ''),
    // "KMF": Currency(code: "KMF", symbol: '', icon: '', title: ''),
    // "KPW": Currency(code: "KPW", symbol: '', icon: '', title: ''),
    // "KRW": Currency(code: "KRW", symbol: '', icon: '', title: ''),
    // "KWD": Currency(code: "KWD", symbol: '', icon: '', title: ''),
    // "KYD": Currency(code: "KYD", symbol: '', icon: '', title: ''),
    // "KZT": Currency(code: "KZT", symbol: '', icon: '', title: ''),
    // "LAK": Currency(code: "LAK", symbol: '', icon: '', title: ''),
    // "LBP": Currency(code: "LBP", symbol: '', icon: '', title: ''),
    // "LD": Currency(code: "LD", symbol: '', icon: '', title: ''),
    // "LKR": Currency(code: "LKR", symbol: '', icon: '', title: ''),
    // "LRD": Currency(code: "LRD", symbol: '', icon: '', title: ''),
    // "LSL": Currency(code: "LSL", symbol: '', icon: '', title: ''),
    // "LTC": Currency(code: "LTC", symbol: '', icon: '', title: ''),
    // "LYD": Currency(code: "LYD", symbol: '', icon: '', title: ''),
    // "MAD": CurrencyCard(code: "MAD", symbol: '', icon: '', title: ''),
    // "MDL": CurrencyCard(code: "MDL", symbol: '', icon: '', title: ''),
    // "MGA": CurrencyCard(code: "MGA", symbol: '', icon: '', title: ''),
    // "MKD": CurrencyCard(code: "MKD", symbol: '', icon: '', title: ''),
    // "MMK": CurrencyCard(code: "MMK", symbol: '', icon: '', title: ''),
    // "MNT": CurrencyCard(code: "MNT", symbol: '', icon: '', title: ''),
    // "MOP": CurrencyCard(code: "MOP", symbol: '', icon: '', title: ''),
    // "MRO": CurrencyCard(code: "MRO", symbol: '', icon: '', title: ''),
    // "MRU": CurrencyCard(code: "MRU", symbol: '', icon: '', title: ''),
    // "MUR": CurrencyCard(code: "MUR", symbol: '', icon: '', title: ''),
    // "MVR": CurrencyCard(code: "MVR", symbol: '', icon: '', title: ''),
    // "MWK": CurrencyCard(code: "MWK", symbol: '', icon: '', title: ''),
    // "MXN": CurrencyCard(code: "MXN", symbol: '', icon: '', title: ''),
    // "MYR": CurrencyCard(code: "MYR", symbol: '', icon: '', title: ''),
    // "MZN": CurrencyCard(code: "MZN", symbol: '', icon: '', title: ''),
    // "NAD": CurrencyCard(code: "NAD", symbol: '', icon: '', title: ''),
    // "NGN": CurrencyCard(code: "NGN", symbol: '', icon: '', title: ''),
    // "NIO": CurrencyCard(code: "NIO", symbol: '', icon: '', title: ''),
    // "NOK": CurrencyCard(code: "NOK", symbol: '', icon: '', title: ''),
    // "NPR": CurrencyCard(code: "NPR", symbol: '', icon: '', title: ''),
    // "NXT": CurrencyCard(code: "NXT", symbol: '', icon: '', title: ''),
    // "NZD": CurrencyCard(code: "NZD", symbol: '', icon: '', title: ''),
    // "OMR": CurrencyCard(code: "OMR", symbol: '', icon: '', title: ''),
    // "PAB": CurrencyCard(code: "PAB", symbol: '', icon: '', title: ''),
    // "PEN": CurrencyCard(code: "PEN", symbol: '', icon: '', title: ''),
    // "PGK": CurrencyCard(code: "PGK", symbol: '', icon: '', title: ''),
    // "PHP": CurrencyCard(code: "PHP", symbol: '', icon: '', title: ''),
    // "PKR": CurrencyCard(code: "PKR", symbol: '', icon: '', title: ''),
    // "PLN": CurrencyCard(code: "PLN", symbol: '', icon: '', title: ''),
    // "PYG": CurrencyCard(code: "PYG", symbol: '', icon: '', title: ''),
    // "QAR": CurrencyCard(code: "QAR", symbol: '', icon: '', title: ''),
    // "RON": CurrencyCard(code: "RON", symbol: '', icon: '', title: ''),
    // "RSD": CurrencyCard(code: "RSD", symbol: '', icon: '', title: ''),
    "RUB": Currency(
      code: "RUB",
      symbol: '₽',
      icon: '🇷🇺',
      title: 'Российский рубль',
      rate: 0,
      isEnable: false,
    ),
    // "RWF": CurrencyCard(code: "RWF", symbol: '', icon: '', title: ''),
    // "SAR": CurrencyCard(code: "SAR", symbol: '', icon: '', title: ''),
    // "SBD": CurrencyCard(code: "SBD", symbol: '', icon: '', title: ''),
    // "SCR": CurrencyCard(code: "SCR", symbol: '', icon: '', title: ''),
    // "SDG": CurrencyCard(code: "SDG", symbol: '', icon: '', title: ''),
    // "SEK": CurrencyCard(code: "SEK", symbol: '', icon: '', title: ''),
    // "SGD": CurrencyCard(code: "SGD", symbol: '', icon: '', title: ''),
    // "SHP": CurrencyCard(code: "SHP", symbol: '', icon: '', title: ''),
    // "SLL": CurrencyCard(code: "SLL", symbol: '', icon: '', title: ''),
    // "SOS": CurrencyCard(code: "SOS", symbol: '', icon: '', title: ''),
    // "SRD": CurrencyCard(code: "SRD", symbol: '', icon: '', title: ''),
    // "SSP": CurrencyCard(code: "SSP", symbol: '', icon: '', title: ''),
    // "STD": CurrencyCard(code: "STD", symbol: '', icon: '', title: ''),
    // "STN": CurrencyCard(code: "STN", symbol: '', icon: '', title: ''),
    // "STR": CurrencyCard(code: "STR", symbol: '', icon: '', title: ''),
    // "SVC": CurrencyCard(code: "SVC", symbol: '', icon: '', title: ''),
    // "SYP": CurrencyCard(code: "SYP", symbol: '', icon: '', title: ''),
    // "SZL": CurrencyCard(code: "SZL", symbol: '', icon: '', title: ''),
    // "THB": CurrencyCard(code: "THB", symbol: '', icon: '', title: ''),
    // "TJS": CurrencyCard(code: "TJS", symbol: '', icon: '', title: ''),
    // "TMT": CurrencyCard(code: "TMT", symbol: '', icon: '', title: ''),
    // "TND": CurrencyCard(code: "TND", symbol: '', icon: '', title: ''),
    // "TOP": CurrencyCard(code: "TOP", symbol: '', icon: '', title: ''),
    // "TRY": CurrencyCard(code: "TRY", symbol: '', icon: '', title: ''),
    // "TTD": CurrencyCard(code: "TTD", symbol: '', icon: '', title: ''),
    // "TWD": CurrencyCard(code: "TWD", symbol: '', icon: '', title: ''),
    // "TZS": CurrencyCard(code: "TZS", symbol: '', icon: '', title: ''),
    // "UAH": CurrencyCard(code: "UAH", symbol: '', icon: '', title: ''),
    // "UGX": CurrencyCard(code: "UGX", symbol: '', icon: '', title: ''),
    "USD": Currency(
      code: "USD",
      symbol: '\$',
      icon: '🇺🇸',
      title: 'Доллар',
      rate: 0,
      isEnable: false,
    ),
    // "UYU": CurrencyCard(code: "UYU", symbol: '', icon: '', title: ''),
    // "UZS": CurrencyCard(code: "UZS", symbol: '', icon: '', title: ''),
    // "VEF_BLKMKT": CurrencyCard(code: "VEF_BLKMKT", symbol: '', icon: '', title: ''),
    // "VEF_DICOM": CurrencyCard(code: "VEF_DICOM", symbol: '', icon: '', title: ''),
    // "VEF_DIPRO": CurrencyCard(code: "VEF_DIPRO", symbol: '', icon: '', title: ''),
    // "VES": CurrencyCard(code: "VES", symbol: '', icon: '', title: ''),
    // "VND": CurrencyCard(code: "VND", symbol: '', icon: '', title: ''),
    // "VUV": CurrencyCard(code: "VUV", symbol: '', icon: '', title: ''),
    // "WST": CurrencyCard(code: "WST", symbol: '', icon: '', title: ''),
    // "XAF": CurrencyCard(code: "XAF", symbol: '', icon: '', title: ''),
    // "XAG": CurrencyCard(code: "XAG", symbol: '', icon: '', title: ''),
    // "XAU": CurrencyCard(code: "XAU", symbol: '', icon: '', title: ''),
    // "XCD": CurrencyCard(code: "XCD", symbol: '', icon: '', title: ''),
    // "XDR": CurrencyCard(code: "XDR", symbol: '', icon: '', title: ''),
    // "XMR": CurrencyCard(code: "XMR", symbol: '', icon: '', title: ''),
    // "XOF": CurrencyCard(code: "XOF", symbol: '', icon: '', title: ''),
    // "XPD": CurrencyCard(code: "XPD", symbol: '', icon: '', title: ''),
    // "XPF": CurrencyCard(code: "XPF", symbol: '', icon: '', title: ''),
    // "XPT": CurrencyCard(code: "XPT", symbol: '', icon: '', title: ''),
    // "XRP": CurrencyCard(code: "XRP", symbol: '', icon: '', title: ''),
    // "YER": CurrencyCard(code: "YER", symbol: '', icon: '', title: ''),
    // "ZAR": CurrencyCard(code: "ZAR", symbol: '', icon: '', title: ''),
    // "ZMW": CurrencyCard(code: "ZMW", symbol: '', icon: '', title: ''),
    // "ZWL": CurrencyCard(code: "ZWL", symbol: '', icon: '', title: ''),
    // "NMC": CurrencyCard(code: "NMC", symbol: '', icon: '', title: ''),
    // "PPC": CurrencyCard(code: "PPC", symbol: '', icon: '', title: ''),
    // "NVC": CurrencyCard(code: "NVC", symbol: '', icon: '', title: ''),
    // "XPM": CurrencyCard(code: "XPM", symbol: '', icon: '', title: ''),
    // "EAC": CurrencyCard(code: "EAC", symbol: '', icon: '', title: ''),
    // "VTC": CurrencyCard(code: "VTC", symbol: '', icon: '', title: ''),
    // "EMC": CurrencyCard(code: "EMC", symbol: '', icon: '', title: ''),
    // "FCT": CurrencyCard(code: "FCT", symbol: '', icon: '', title: ''),
    // "BNB": CurrencyCard(code: "BNB", symbol: '', icon: '', title: ''),
  };
}
